# Generated by Django 3.0.8 on 2020-07-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heartrate',
        ),
    ]
