# Generated by Django 3.1 on 2020-08-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200816_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pers_age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
    ]
