# Generated by Django 3.1 on 2020-08-14 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200815_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time_interaction',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='LONG', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 0, 23, 22, 133211)),
        ),
    ]
