# Generated by Django 3.1 on 2020-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200821_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='close',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='interaction',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=7, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lay',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='reply',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
    ]
