# Generated by Django 3.1 on 2020-08-14 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200815_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='current_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 0, 28, 36, 949324)),
        ),
    ]
