# Generated by Django 3.1 on 2020-08-14 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200815_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='current_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 1, 30, 24, 878199)),
        ),
    ]
