# Generated by Django 3.1 on 2020-08-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200821_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='duration',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], default='Medium', max_length=30, null=True),
        ),
    ]
