# Generated by Django 3.1 on 2020-08-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_1', models.CharField(max_length=30)),
                ('test_field_2', models.CharField(max_length=30)),
            ],
        ),
    ]
