# Generated by Django 3.1 on 2020-08-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
