# Generated by Django 3.1 on 2020-08-15 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20200815_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='time_interaction',
        ),
        migrations.AlterField(
            model_name='person',
            name='current_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 23, 30, 10, 48980)),
        ),
    ]
