# Generated by Django 3.1 on 2020-08-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_auto_20200815_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_datetime',
        ),
    ]
