# Generated by Django 3.1 on 2020-08-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)]),
        ),
    ]
