# Generated by Django 3.1 on 2020-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20200816_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
    ]
