# Generated by Django 3.1 on 2020-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20200816_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3),
        ),
    ]
