# Generated by Django 3.1 on 2020-08-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20200816_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
